### PR TITLE
Add aha wistiki version in wistiki.jxon config file

### PR DESCRIPTION
**Pull request by ouquoi**

### CODE REVIEW

**Comment by ouquoi** [comment]
I try to understand how to add a new wistiki device. Perhaps some other modification are need ...

**Comment by sarakha63** [comment]
yes needs some modification on pyton side too. but very little as witsiki will only be used for presence. you can take example on fitbit device

**Comment by ouquoi** [comment]
i have checked wistiki.py and fitbit.py but i don't see the management of multiple device in this py script.

Perhaps it will better (sure it will) if you do it. I will check your PR to understand how it works.

thanks

**Comment by sarakha63** [comment]
Just need to have the info of it's name or else to add in the isvalid function

**Pull request closed without merging**
